language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install future configparser paramiko"
script:
  - ./src/ROCED/scale.py test
  - ./src/ROCED/scale.py --debug --iterations 10 --config src/ROCED/roced_fake.config standalone
